name: Setup
description: Install tools and dependencies

runs:
  using: "composite"
  steps:
    - name: Install Bun
      uses: oven-sh/setup-bun@0c5077e51419868618aeaa5fe8019c62421857d6 # v2.2.0
      with:
        bun-version-file: npm/package.json
    - name: Set up Docker
      uses: docker/setup-docker-action@1a6edb0ba9ac496f6850236981f15d8f9a82254d # 5.0.0
    - name: Install Dependencies
      shell: bash
      run: |
        pushd npm
          bun install --frozen-lockfile
        popd
        pushd demo
          bun install --frozen-lockfile
        popd
